### ISSUE TITLE
Support for sway?

### ISSUE THREAD

**Issue by AndreasBackx** [pitkley/i3nator#30]
I was wondering whether this project supports sway. If not, would it be possible to add support for sway?

**Comment by pitkley** [comment]
Hi @AndreasBackx. This project currently does not support sway; mostly because I don't use it, but also because sway does not (yet) have support for the `append_layout` command that is required for i3nator to work.

There [seems to be a PR](https://github.com/swaywm/sway/pull/3022), although it seems to have been abandoned.

Once sway supports the `append_layout` feature I'll gladly take contributions on support for it, right now it simply isn't possible.

Thanks for your interest!

**Comment by AndreasBackx** [comment]
Ah bummer! I wanted to get something similar to tmuxinator but don't want to change my muscle memory for stuff like CTRL+SHIFT+C and the like. Thank you though.
